export const GET_POKEMON = {
  REQUEST: 'GET_POKEMON_REQUEST',
  SUCCESS: 'GET_POKEMON_SUCCESS',
  ERROR: 'GET_POKEMON_ERROR',
};

export const GET_POKEMON_DETAILS = {
  REQUEST: 'GET_POKEMON_DETAILS_REQUEST',
  SUCCESS: 'GET_POKEMON_DETAILS_SUCCESS',
  ERROR: 'GET_POKEMON_DETAILS_ERROR',
};
